### ISSUE TITLE
Relations raises an exception with Wagtail 1.3.1

### ISSUE THREAD

**Issue by robmoggach** [rfosterslo/wagtailplus#13]
I'm getting the following error(s). Let me know if you see a quick fix and I'll reenable the package and try again.

    ± |django U:489 ?:15 ✗| → python manage.py makemigrations
    Traceback (most recent call last):
      File "manage.py", line 19, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
        django.setup()
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
        mod = import_module(mod_path)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/wagtailplus/wagtailrelations/apps.py", line 10, in <module>
        from wagtailplus.utils.edit_handlers import add_panel_to_edit_handler
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/wagtailplus/utils/edit_handlers.py", line 4, in <module>
        from wagtail.wagtailadmin.edit_handlers import ObjectList
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 5, in <module>
        from modelcluster.forms import ClusterForm, ClusterFormMetaclass
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/modelcluster/forms.py", line 18, in <module>
        from modelcluster.models import get_all_child_relations
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/modelcluster/models.py", line 152, in <module>
        class ClusterableModel(models.Model):
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
        app_config = apps.get_containing_app_config(module)
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
        self.check_apps_ready()
      File "/Users/rob/.virtualenvs/wagtail/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
        raise AppRegistryNotReady("Apps aren't loaded yet.")
    django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by rfosterslo** [comment]
Doesn't look like a quick fix - Django 1.9 completely changed how apps are loaded.

**Comment by rfosterslo** [comment]
Fixed in v0.3.7.
